### ISSUE TITLE
Some errors in your files.

### ISSUE THREAD

**Issue by eyecuejohn** [bryceandy/laravel_pesapal#1]
Hi Bryce. Thanks for a great package that is saving me time on an integration. It has taken much longer because of some errors in your code which I would like to point out.

1. checkStatus.php file has class pesapalCheckStatus which has to be corrected in name to pesapalCheckStatus.php or it cannot be found in Laravel and throws an error
2. In the same file on line 20
 $consumer_secret 	= config('pesapal.consumer_key'); should be changed to 
$consumer_secret 	= config('pesapal.consumer_secret'); as it brings an error by returning no values to the array.
3. In TransactionController.php the variables for consumer_key and consumer_secret should be referred to from the config file and not from the .env file so change as follows:
         $consumer_key       = config('pesapal.consumer_key');
        $consumer_secret    = config('pesapal.consumer_secret');
otherwise this also brings errors as well.

**Comment by bryceandy** [comment]
Hi @eyecuejohn, for points 2 & 3 they have already been rectified in the coming version 1.0.2

However for point 1, renaming the checkStatus.php file doesn't change the accessibility of the pesapalCheckStatus as you can see below, it is autodetected before I complete typing.
![image](https://user-images.githubusercontent.com/11915180/59758810-6c86c780-9297-11e9-93ad-c419e5e01997.png)

At what point did you arrive to the error in point 1?

**Comment by eyecuejohn** [comment]
Hi @bryceandy it is possible I was mixing the error of invalid signature returned and associating it with that issue. Otherwise the package is working fine after I corrected 2 & 3. Thanks again!
